services:
  - type: web
    name: casino-app
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    mounts:
      - path: /opt/render/project/src/data
        name: data
    healthCheckPath: /healthz

disks:
  - name: data
    mountPath: /opt/render/project/src/data
    sizeGB: 1


